In [11]:
import pandas as pd
import numpy as np

In [12]:
sentence = "Discover the power of regular expressions with this tutorial."
token_sequence1 = sentence.split()

In [15]:
token_sequence = str.split(sentence)
vocab = sorted(set(token_sequence))
print(vocab)

['Discover', 'expressions', 'of', 'power', 'regular', 'the', 'this', 'tutorial.', 'with']


In [14]:
num_tokens = len(token_sequence)
vocab_size = len(vocab)
# print(vocab_size)

9


In [24]:
onehot_vectors = np.zeros((num_tokens, vocab_size), int)
for i, word in enumerate(token_sequence):
    # print(i, vocab.index(word), word)
    onehot_vectors[i, vocab.index(word)] = 1  ### 
print(onehot_vectors)

[[1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0]
 [0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 1 0]]


In [25]:
pd.DataFrame(onehot_vectors, columns=vocab)

Discover  expressions  of  power  regular  the  this  tutorial.  with
0         1            0   0      0        0    0     0          0     0
1         0            0   0      0        0    1     0          0     0
2         0            0   0      1        0    0     0          0     0
3         0            0   1      0        0    0     0          0     0
4         0            0   0      0        1    0     0          0     0
5         0            1   0      0        0    0     0          0     0
6         0            0   0      0        0    0     0          0     1
7         0            0   0      0        0    0     1          0     0
8         0            0   0      0        0    0     0          1     0