**Numpy**

NumPy is an open source mathematical and scientific computing library for Python programming tasks. The name NumPy is shorthand for Numerical Python. The NumPy library offers a collection of high-level mathematical functions including support for multi-dimensional arrays, masked arrays and matrices. NumPy also includes various logical and mathematical capabilities for those arrays such as shape manipulation, sorting, selection, linear algebra, statistical operations, random number generation and discrete Fourier transforms.



You might hear of a 0-D (zero-dimensional) array referred to as a “scalar”, a 1-D (one-dimensional) array as a “vector”, a 2-D (two-dimensional) array as a “matrix”, or an N-D (N-dimensional, where “N” is typically an integer greater than 2) array as a “tensor”. For clarity, it is best to avoid the mathematical terms when referring to an array because the mathematical objects with these names behave differently than arrays (e.g. “matrix” multiplication is fundamentally different from “array” multiplication), and there are other objects in the scientific Python ecosystem that have these names (e.g. the fundamental data structure of PyTorch is the “tensor”).

In [11]:
import numpy as np


### create array using numpy
## create a 1D array

arr1 = np.array([1,2,3,4,5])
print(arr1)
print(arr1.shape)
print(type(arr1))

[1 2 3 4 5]
(5,)
<class 'numpy.ndarray'>


In [ ]:
## 1D array
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5) 

array([[1, 2, 3, 4, 5]])

In [13]:
## 2D array
arr2=np.array([[1, 2, 3, 4, 5],[2,7,3,4,5]])
arr2.shape

(2, 5)

In [15]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

It is familiar practice in mathematics to refer to elements of a matrix by the row index first and the column index second. This happens to be true for two-dimensional arrays, but a better mental model is to think of the column index as coming last and the row index as second to last. This generalizes to arrays with any number of dimensions.

In [17]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
## identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
arr = np.array([[1,2,3,4,5],[9,5,7,9,2]])

print("Array:\n" , arr)
print("Shape:" , arr.shape)
print("Nbr of dimensions:" , arr.ndim)
print("Size (nbr of elements):" , arr.size)
print("Data type:" , arr.dtype)
print("Item size (in bytes):" , arr.itemsize)


Array:
 [[1 2 3 4 5]
 [9 5 7 9 2]]
Shape: (2, 5)
Nbr of dimensions: 2
Size (nbr of elements): 10
Data type: int64
Item size (in bytes): 8


In [25]:
## Numpy vectorised operation

arr1=np.array([1,2,3,4,5])
arr2=np.array([2,3,4,5,7])

### Element wise addition
print("Addition:" , arr1+arr2)

### Element wise substraction
print("Substraction:" , arr1-arr2)

### Element wise Multiplication
print("Multiplication:" , arr1*arr2)

### Multiplication wise division
print("Division:" , arr1/arr2)

Addition: [ 3  5  7  9 12]
Substraction: [-1 -1 -1 -1 -2]
Multiplication: [ 2  6 12 20 35]
Division: [0.5        0.66666667 0.75       0.8        0.71428571]


In [29]:
## Universal function
arr=np.array([2,3,4,5,6])

#square root
print(np.sqrt(arr))

## Exponential
print(np.exp(arr))

## Sine
print(np.sin(arr))

## log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [32]:
## Array Slicing 
arr = np.array([[1,2,3,4],[8,3,4,5],[9,3,6,7]])
print("Array: \n", arr)

Array: 
 [[1 2 3 4]
 [8 3 4 5]
 [9 3 6 7]]


In [35]:
arr[0][0]

1

In [36]:
arr[1:,2:]

array([[4, 5],
       [6, 7]])

In [39]:
arr[:2,2:]

array([[3, 4],
       [4, 5]])

In [40]:
## Modify array elements

arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  8   3   4   5]
 [  9   3   6   7]]


In [8]:
## Statistical Concept- Normalization
## to have a mean of 0 and SD of 1

data = np.array([1,2,3,4,5])

# Calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)
print(std_dev)

## Normalize the data
normalized_data = (data - mean) / std_dev
print("Normalized data:", normalized_data)

1.4142135623730951
Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [9]:

data = np.array([1,2,3,4,5])

## Mean
mean = np.mean(data)
print("mean:", mean)
## Median
median = np.median(data)
print("median:", median)
## Standard deviation
std = np.std(data)
print("std:", std)
## Variance
var = np.var(data)
print("var:", var)


mean: 3.0
median: 3.0
std: 1.4142135623730951
var: 2.0


In [14]:
## logical operation
data = np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>=5) & (data<8) ]

array([5, 6, 7])