In [1]:
import numpy as np

In [3]:
data = [1, 8.2, 0, 6, 2.9]
arr = np.array(data)
arr

array([1. , 8.2, 0. , 6. , 2.9])

In [4]:
data1 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data1)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
arr2.shape # 2 rows 4 column

(2, 4)

In [6]:
arr2.ndim # arr2 has 2 dimension i.e. 2 rows

2

In [7]:
arr2.dtype

dtype('int64')

In [13]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.zeros((5,2,3)) # pass in tuple for higher dimensional array.

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [12]:
np.empty((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
np.arange(stop=8, step=2)

array([0, 2, 4, 6])

In [20]:
np.ones_like([4,2,4])

array([1, 1, 1])

In [30]:
np.full((3,3),[1,2,3])

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [33]:
np.identity(2) # eye or identity

array([[1., 0.],
       [0., 1.]])

In [36]:
test_arr = np.arange(3)
test_arr.dtype

dtype('int64')

In [37]:
test_f = test_arr.astype(np.float64)   # can be used to convert string to float
test_f

array([0., 1., 2.])