In [4]:
import numpy as np # Orienation in Numpy is given by brackets, ouutermost bracket 
asList = [1,2,3]
asArray = np.array([1,2,3]) #1D vector orientationless array
rowVec = np.array([[1,2,3]]) # row vector
colVec = np.array([[1],[2],[3]]) # column vector
print(np.shape(asArray))
print(asArray.shape) # same as above
print(np.shape(rowVec)) # row orientation (row, column)
print(np.shape(colVec)) # column orientation
print(len(asArray)) 
print(len(colVec))

(3,)
(3,)
(1, 3)
(3, 1)
3
3


In [7]:
# Addition of vectors
import numpy as np
v = np.array([4,7,3])
w = np.array([3,5,8])
u = np.array([3,5,8,10])
print(v+w)
#print(w+u) # error not same dimension

[ 7 12 11]


ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [4]:
# broadcasting exist in python, not exist in linear algebra. Add row vector to column vector with same dimensions
# Broadcasting essentially means to repeat an operation multiple times between one
#vector and each element of another vector.
v = np.array([[4,7,3]]) # row vector
w = np.array([[3,5,8]]).T # column vector
print(v+w)

[[ 7 10  6]
 [ 9 12  8]
 [12 15 11]]


In [6]:
v = np.array([1,2,3,7,9])
print(len(v)) # maths dimensionality
print(np.linalg.norm(v)) # maths magnitude, length, norm

5
12.0
